### ISSUE TITLE
destroy an instance of dual-range-bar

### ISSUE THREAD

**Issue by gautiermichelin** [celestialphineas/dual-range-bar#15]
How to destroy an instance of dual-range-bar ?  Could you add it to the documentation ?

**Comment by celestialphineas** [comment]
Since `dual-range-bar` is a minimal VanillaJS component, it's easy to remove an instance from the DOM, simply by deleting the container element that you initalized on:

```javascript
document.querySelector('#dhr').remove() // where `#dhr` is the container element of a `DualHRange`
```

If you are worried about the JavaScript object that is referencing the element, you may reset that variable and leave it up to the JS engine to take care of the rest.
